In [90]:
import os
import sys
sys.path.insert(0, os.path.abspath('../..'))

import numpy as np
from module.base.network import Network
import module.components.utils as utils

In [126]:
A = np.ones(shape = (2,2,2,25)) * 0.5

In [127]:
indices = np.random.randint(0, 25, size = (2,2,2))

In [128]:
expA = A.reshape((-1,25))
expA.shape

(8, 25)

In [129]:
expindex = indices.flatten()
expindex

array([ 0,  9, 13, 15,  7, 15, 19,  3])

In [130]:
copy = expA[np.arange(8), expindex]

In [131]:
expA[np.arange(8), expindex] = 1

In [132]:
copy

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

In [134]:
expA[np.arange(8), expindex]

array([1., 1., 1., 1., 1., 1., 1., 1.])